package com.boot.security.jwt.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.boot.security.jwt.model.User;
import com.boot.security.jwt.model.UserRequest;
import com.boot.security.jwt.model.UserResponse;
import com.boot.security.jwt.service.UiUserService;
import com.boot.security.jwt.utilitiy.JwtUtil;

@RestController
@RequestMapping(value = "/user")
public class UserController {
	@Autowired
	private UiUserService userService;// HAS-A
	@Autowired
	private JwtUtil util;
	
	@Autowired
	private AuthenticationManager authenticationManager;

	// 1. save user Data in db
	@PostMapping("/save")
	public ResponseEntity<String> saveUser(@RequestBody User user) {

		Integer userId = userService.saveUser(user);

		String body = "User :" + userId + " saveed";
		// return new ResponseEntity<String>(body,HttpStatus.OK);//same thing
		return ResponseEntity.ok(body);
	}
	

	//2. validate user and generate token (login)
	
	@PostMapping(value = "/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest request){
		
		// validate user name and password with database
		
		authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(request.getUsername(), request.getPassword()));
	
		String token = util.generateToken(request.getUsername());
		return ResponseEntity.ok(
				new UserResponse(token,"Success ! Generated By Vitthal"));
	}
	
	
	//3. after login only
	@PostMapping("/welcome")
	public ResponseEntity<String> accessData(Principal p){
		return ResponseEntity.ok("Hello User!  " + p.getName());
	}
}
